-- 创建数据库
CREATE DATABASE cs209a_stackoverflow;

-- 切换到目标数据库
\c cs209a_stackoverflow;

-- 用户表（存储问题/回答/评论的作者信息）
CREATE TABLE users (
    user_id BIGINT PRIMARY KEY,
    account_id BIGINT,
    reputation INTEGER NOT NULL,
    user_type VARCHAR(20) NOT NULL,
    accept_rate SMALLINT,
    profile_image VARCHAR(255),
    display_name VARCHAR(100) NOT NULL,
    link VARCHAR(255)
);

-- 给users表添加列注释
COMMENT ON COLUMN users.reputation IS '用户声望值';
COMMENT ON COLUMN users.user_type IS '用户类型';
COMMENT ON COLUMN users.accept_rate IS '问题接受率（百分比）';
COMMENT ON COLUMN users.profile_image IS '头像URL';
COMMENT ON COLUMN users.display_name IS '显示名称';
COMMENT ON COLUMN users.link IS '用户主页链接';

-- 创建索引
CREATE INDEX idx_user_account_id ON users(account_id);

-- 问题表
CREATE TABLE questions (
    question_id BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    is_answered BOOLEAN NOT NULL,
    view_count INTEGER NOT NULL,
    answer_count INTEGER NOT NULL,
    score INTEGER NOT NULL,
    accepted_answer_id BIGINT,
    creation_date BIGINT NOT NULL,
    last_edit_date BIGINT,
    last_activity_date BIGINT NOT NULL,
    protected_date BIGINT,
    content_license VARCHAR(50),
    link VARCHAR(255) NOT NULL,
    -- 外键约束
    CONSTRAINT fk_question_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id)
);

-- 给questions表添加列注释
COMMENT ON COLUMN questions.title IS '问题标题';
COMMENT ON COLUMN questions.body IS '问题内容（HTML格式）';
COMMENT ON COLUMN questions.owner_user_id IS '提问者ID（关联users）';
COMMENT ON COLUMN questions.is_answered IS '是否已回答';
COMMENT ON COLUMN questions.view_count IS '浏览量';
COMMENT ON COLUMN questions.answer_count IS '回答数量';
COMMENT ON COLUMN questions.score IS '得分（赞-踩）';
COMMENT ON COLUMN questions.accepted_answer_id IS '被采纳的回答ID（关联answers）';
COMMENT ON COLUMN questions.creation_date IS '创建时间戳（秒）';
COMMENT ON COLUMN questions.last_edit_date IS '最后编辑时间戳';
COMMENT ON COLUMN questions.last_activity_date IS '最后活动时间戳';
COMMENT ON COLUMN questions.protected_date IS '保护时间戳';
COMMENT ON COLUMN questions.content_license IS '内容许可证';
COMMENT ON COLUMN questions.link IS '问题链接';

-- 创建索引
CREATE INDEX idx_question_owner ON questions(owner_user_id);
CREATE INDEX idx_question_creation_date ON questions(creation_date);
CREATE INDEX idx_question_score ON questions(score);
CREATE INDEX idx_question_is_answered ON questions(is_answered);

-- 问题-标签关联表（一个问题有多个标签则存储多行）
CREATE TABLE question_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    tag VARCHAR(50) NOT NULL,
    -- 外键约束
    CONSTRAINT fk_tag_question FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE,
    -- 唯一约束（同一问题不能有重复的标签）
    CONSTRAINT uk_question_tag UNIQUE (question_id, tag)
);

-- 给question_tags表添加列注释
COMMENT ON COLUMN question_tags.question_id IS '问题ID';
COMMENT ON COLUMN question_tags.tag IS '标签名称';

-- 创建索引
CREATE INDEX idx_question_tag_question_id ON question_tags(question_id);
CREATE INDEX idx_question_tag_tag ON question_tags(tag);

-- 回答表
CREATE TABLE answers (
    answer_id BIGINT PRIMARY KEY,
    question_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    body TEXT NOT NULL,
    is_accepted BOOLEAN NOT NULL,
    score INTEGER NOT NULL,
    creation_date BIGINT NOT NULL,
    last_edit_date BIGINT,
    last_activity_date BIGINT NOT NULL,
    content_license VARCHAR(50),
    -- 外键约束
    CONSTRAINT fk_answer_question FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id)
);

-- 给answers表添加列注释
COMMENT ON COLUMN answers.question_id IS '问题ID';
COMMENT ON COLUMN answers.owner_user_id IS '回答者ID（关联users）';
COMMENT ON COLUMN answers.body IS '回答内容（HTML格式）';
COMMENT ON COLUMN answers.is_accepted IS '是否被采纳';
COMMENT ON COLUMN answers.score IS '得分（赞-踩）';
COMMENT ON COLUMN answers.creation_date IS '创建时间戳';
COMMENT ON COLUMN answers.last_edit_date IS '最后编辑时间戳';
COMMENT ON COLUMN answers.last_activity_date IS '最后活动时间戳';
COMMENT ON COLUMN answers.content_license IS '内容许可证';

-- 创建索引
CREATE INDEX idx_answer_question ON answers(question_id);
CREATE INDEX idx_answer_owner ON answers(owner_user_id);
CREATE INDEX idx_answer_is_accepted ON answers(is_accepted);

-- 评论表（统一存储问题/回答的评论）
CREATE TABLE comments (
    comment_id BIGINT PRIMARY KEY,
    post_type CHAR(1) NOT NULL,
    post_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    reply_to_user_id BIGINT,
    edited BOOLEAN NOT NULL,
    score INTEGER NOT NULL,
    creation_date BIGINT NOT NULL,
    content_license VARCHAR(50),
    -- 外键约束
    CONSTRAINT fk_comment_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_comment_reply FOREIGN KEY (reply_to_user_id) REFERENCES users(user_id)
);

-- 给comments表添加列注释
COMMENT ON COLUMN comments.post_type IS '关联类型（Q-question/A-answer）';
COMMENT ON COLUMN comments.post_id IS '关联ID（问题ID或回答ID）';
COMMENT ON COLUMN comments.owner_user_id IS '评论者ID（关联users）';
COMMENT ON COLUMN comments.reply_to_user_id IS '回复目标用户ID（关联users）';
COMMENT ON COLUMN comments.edited IS '是否已编辑';
COMMENT ON COLUMN comments.score IS '评论得分';
COMMENT ON COLUMN comments.creation_date IS '创建时间戳';
COMMENT ON COLUMN comments.content_license IS '内容许可证';

-- 创建索引
CREATE INDEX idx_comment_post ON comments(post_type, post_id);
CREATE INDEX idx_comment_owner ON comments(owner_user_id);